/*
 * This source file was generated by the Gradle 'init' task
 */
package src;

import static org.mockito.Mockito.when;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

@SpringBootTest
class DateServiceTest {

    @Autowired
    private DateService dateService;

    @MockitoBean
    private DateUtil dateUtil;

    @Test
    public void printNowTest() {

        when(dateUtil.getNow()).thenReturn(LocalDateTime.of(2025,1,1,12,34,56));

        dateService.printNow();
    }
}
